### ISSUE TITLE
Have any option to print log as JSON format?

### ISSUE THREAD

**Issue by hasancse91** [Milad-Akarie/pretty_dio_logger#16]
Hey there!
Thank you for your awesome library.

Using your library I can print log like this format:
```
{
    foo: "bar" // foo is here without double quote
}
```

Have any way to print the JSON with actual format?

```
{
   "foo": "bar" // foo is here inside double quote.
}
```
I need to print log in JSON format. Is it possible in your library with any configuration? Or have any plan to do something like that?
Thanks.

**Comment by Milad-Akarie** [comment]
done by default now

**Comment by hasancse91** [comment]
Thanks.
