### ISSUE TITLE
How to use debugPrint

### ISSUE THREAD

**Issue by sebastianbuechler** [Milad-Akarie/pretty_dio_logger#17]
I want to use the recommended debugPrint as logPrint option:
`    _dio.interceptors.add(
      PrettyDioLogger(
        logPrint: debugPrint
      ),
)
`

However, I get an error that it is not valid because debugPrint is of the wrong type:
`The argument type 'void Function(String?, {int? wrapWidth})' can't be assigned to the parameter type 'void Function(Object)'.dart(argument_type_not_assignable)`

How is this intended to work?

**Comment by FelipeFernandesLeandro** [comment]
> I want to use the recommended debugPrint as logPrint option:
> ` _dio.interceptors.add( PrettyDioLogger( logPrint: debugPrint ), )`
> 
> However, I get an error that it is not valid because debugPrint is of the wrong type:
> `The argument type 'void Function(String?, {int? wrapWidth})' can't be assigned to the parameter type 'void Function(Object)'.dart(argument_type_not_assignable)`
> 
> How is this intended to work?

` void appDebugPrint(Object message) {
      debugPrint(message.toString());
  }
  
  dio
      ..options.baseUrl = url
      ..interceptors.add(PrettyDioLogger(logPrint: appDebugPrint));
`

**Comment by patevs** [comment]
> > I want to use the recommended debugPrint as logPrint option:
> > ` _dio.interceptors.add( PrettyDioLogger( logPrint: debugPrint ), )`
> > However, I get an error that it is not valid because debugPrint is of the wrong type:
> > `The argument type 'void Function(String?, {int? wrapWidth})' can't be assigned to the parameter type 'void Function(Object)'.dart(argument_type_not_assignable)`
> > How is this intended to work?
> 
> ```
>   void appDebugPrint(Object message) {
>       debugPrint(message.toString());
>   }
>   
>   dio
>       ..options.baseUrl = url
>       ..interceptors.add(PrettyDioLogger(logPrint: appDebugPrint));
> ```

In one line:
```dart
	dio..interceptors.add(PrettyDioLogger(logPrint: (o) => debugPrint(o.toString())));
```
