### ISSUE TITLE
Unnecessary spaces using custom contructor

### ISSUE THREAD

**Issue by dungnv2602** [Milad-Akarie/pretty_dio_logger#2]
There are empty spaces, which I believe come from responseBody, when I set responseBody: false.

`  dio.interceptors.add(
    PrettyDioLogger(
      requestHeader: false,
      requestBody: true,
      responseBody: false,
      responseHeader: false,
      error: true,
      compact: true,
      maxWidth: 90,
    ),
  );`

![take_01](https://user-images.githubusercontent.com/19910775/66269619-c924e700-e874-11e9-9ba4-86a50436718a.png)

In this case, these empty spaces should be removed.

**Comment by Milad-Akarie** [comment]
@dungnv2602  Thanks, buddy. I'll look into it.
