### ISSUE TITLE
Error: Member not found: 'response'. (after upgrading to dio 5.0.0)

### ISSUE THREAD

**Issue by ironda2020** [Milad-Akarie/pretty_dio_logger#29]
Hi,
i get this error today after upgrading to dio 5.0.0
**/C:/Users/pc/AppData/Local/Pub/Cache/hosted/pub.dev/pretty_dio_logger-1.2.0-beta-1/lib/pretty_dio_logger.dart:89:36: Error: Member not found: 'response'.
      if (err.type == DioErrorType.response) {
                                   ^^^^^^^^
Target kernel_snapshot failed: Exception**

i think that DioErrorType.response is removed from dio 5.0.0 and replaced by DioErrorType.badResponse

**Comment by dmakwt** [comment]
Upgrade the package to v1.3.1 @ironda2020
