### ISSUE TITLE
I added API response time in logs

### ISSUE THREAD

**Issue by nimi0112** [Milad-Akarie/pretty_dio_logger#38]
I added API response time in logs, let me know if you are interested in this feature. I'll open a PR for this.

<img width="997" alt="Screenshot 2023-04-30 at 10 43 24 PM" src="https://user-images.githubusercontent.com/16234261/235367137-b2214845-51ce-4f86-99b4-38aa8c1dde77.png">

**Comment by politefeng** [comment]
great

**Comment by Milad-Akarie** [comment]
done
