### ISSUE TITLE
Remove flutter as dependency

### ISSUE THREAD

**Issue by apiep** [Milad-Akarie/pretty_dio_logger#6]
Hi, I am interested to use this library. But I can not use it for my dart application since it is has flutter as dependency. But when I tried to look into the code, it did not use any flutter related packages.
Care to remove flutter as dependency?

I can work on it and make a PR if you want to :)

**Comment by Milad-Akarie** [comment]
Hey, @apiep it's done v1.1.1
Thanks for reporting.
