### ISSUE TITLE
token的key丢了

### ISSUE THREAD

**Issue by addappcn** [Milad-Akarie/pretty_dio_logger#7]
![image](https://user-images.githubusercontent.com/8097787/80453133-3f488280-895a-11ea-9f5f-0ee0467f54c5.png)

**Comment by MarnoDev** [comment]
You can modify source code like this

![image](https://user-images.githubusercontent.com/14787921/102316328-b184da80-3fb0-11eb-907f-13f1c8ff36bd.png)

```
         for (int i = 0; i < lines; ++i) {
            var multiLineKey = i == 0 ? "$key: " : "";
            logPrint(
                '║${_indent(tabs)} $multiLineKey${msg.substring(i * linWidth, math.min<int>(i * linWidth + linWidth, msg.length))}');
          }
```

![image](https://user-images.githubusercontent.com/14787921/102316408-d37e5d00-3fb0-11eb-8fb0-e618a0862c25.png)

**Comment by Jaybird9633** [comment]
I need help getting into a regions bank i need the username and password ill share the wealth with you it's plenty email me at Jay.tesley2013@gmail.com

**Comment by Milad-Akarie** [comment]
should be fixed
